version: "3.7"
services:
  web:
    container_name: php-lamp
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "changeme"
      MYSQL_DATABASE: "todo"

volumes:
  mariadb:
