version: '3'
services: 
  apache-php:
    build:
      context: ./apache-php
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    links:
      - 'mariadb'
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWROD: "toor"
volumes:
  mariadb: